sudo : required
services:
 - docker

before_install: 
 - gem update --system
 - gem install bundler
 - docker build -t sample -f  Dockerfile.dev .

scripts:
 - docker run  sample npm run test -- --coverage 